spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus_recruitment?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ybwell
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
server:
  port: 8080
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
#  枚举类包路径
application:
  security:
    secret: caohao
  enum:
    default:
      package:
        path: com.caohao.common.enums.impl
